//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    
    public partial class GetInfo_Result1
    {
        public string Dio { get; set; }
        public Nullable<int> Prodato { get; set; }
        public Nullable<double> Zarada { get; set; }
        public int Zaliha { get; set; }
    }
}
