//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    
    public partial class GetModele_Result1
    {
        public int ModelID { get; set; }
        public int ProizvodjacID { get; set; }
        public string Naziv { get; set; }
        public string VrstaModela { get; set; }
    }
}
