//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    
    public partial class GEtNazivDijelovaALl_Result4
    {
        public int DioID { get; set; }
        public string Naziv { get; set; }
        public int Zalihe { get; set; }
        public double Cijena { get; set; }
        public string Sifra { get; set; }
        public int ProizvodjacID { get; set; }
        public string AutaProizvedena { get; set; }
        public string Opis { get; set; }
        public int Kolicina { get; set; }
        public Nullable<double> Popust { get; set; }
        public Nullable<double> Rabat { get; set; }
        public Nullable<int> RacunID { get; set; }
        public Nullable<int> VoziloID { get; set; }
    }
}
