//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    
    public partial class GEtNazivAutaALL_Result2
    {
        public int VoziloID { get; set; }
        public string Naziv { get; set; }
        public double Cijena { get; set; }
        public Nullable<int> Prodato { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<double> Rabat { get; set; }
        public Nullable<double> Popust { get; set; }
    }
}
