//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupci
    {
        public Kupci()
        {
            this.Kvarovi = new HashSet<Kvarovi>();
            this.Pitanja = new HashSet<Pitanja>();
            this.Racuni = new HashSet<Racuni>();
            this.Notifikacija = new HashSet<Notifikacija>();
        }
    
        public int KupacID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Adresa { get; set; }
        public string Lozinka { get; set; }
    
        public virtual ICollection<Kvarovi> Kvarovi { get; set; }
        public virtual ICollection<Pitanja> Pitanja { get; set; }
        public virtual ICollection<Racuni> Racuni { get; set; }
        public virtual ICollection<Notifikacija> Notifikacija { get; set; }
    }
}
