//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifikacija
    {
        public int NotifikacijaID { get; set; }
        public string Naslov { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> Vrijeme { get; set; }
        public Nullable<int> KupacID { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Kupci Kupci { get; set; }
    }
}
