//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdajaServis.Data
{
    using System;
    
    public partial class RacunSelectByDatum_Result1
    {
        public int RacunID { get; set; }
        public int KorisnikID { get; set; }
        public string Opis { get; set; }
        public double Cijena { get; set; }
        public string Komentar { get; set; }
        public double PDV { get; set; }
        public double Ukupno { get; set; }
        public System.DateTime DatumFakture { get; set; }
        public Nullable<System.DateTime> DatumIsporuke { get; set; }
        public string NacinIsporuke { get; set; }
        public int PlacanjeID { get; set; }
        public int KupacID { get; set; }
        public Nullable<decimal> IDKupac { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int VoziloID { get; set; }
        public string Naziv { get; set; }
        public string Godiste { get; set; }
        public string Boja { get; set; }
        public string VrstaMotora { get; set; }
        public string EmisijaCO2 { get; set; }
        public int ModelID { get; set; }
        public byte[] SlikaThumg { get; set; }
        public byte[] Slika { get; set; }
        public double Cijena1 { get; set; }
        public string Oprema { get; set; }
        public string SnagaMotora { get; set; }
        public string BrojSasije { get; set; }
        public string ZapreminaMotora { get; set; }
        public string ZapreminaGepeka { get; set; }
        public string Duzina { get; set; }
        public string Tezina { get; set; }
        public string Klima { get; set; }
        public Nullable<int> BrojSjedista { get; set; }
        public string Pogon { get; set; }
        public Nullable<int> BrojVrata { get; set; }
        public string OpisSigurnost { get; set; }
        public string Mijenjac { get; set; }
        public string Potrosnja { get; set; }
        public string ObrtniMoment { get; set; }
        public string Sirina { get; set; }
        public string Ubrzanje { get; set; }
        public string MaksimalnaBrzina { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<int> BrojRacun { get; set; }
        public int Kolicina1 { get; set; }
        public Nullable<int> IDVozila { get; set; }
    }
}
