//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdaja {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Poruke {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Poruke() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eProdaja.Poruke", typeof(Poruke).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci su uklonjeni!.
        /// </summary>
        internal static string brisi {
            get {
                return ResourceManager.GetString("brisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguce izbrisati podatke zbog veza!.
        /// </summary>
        internal static string cc {
            get {
                return ResourceManager.GetString("cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste uklonili željene podatke..
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je zauzet.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo, popunite sva polja ili format maila pogresan!.
        /// </summary>
        internal static string fieldError {
            get {
                return ResourceManager.GetString("fieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogresan format!.
        /// </summary>
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste zaključili kupovinu..
        /// </summary>
        internal static string great {
            get {
                return ResourceManager.GetString("great", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo, oznacite pocetak grida!.
        /// </summary>
        internal static string gridError {
            get {
                return ResourceManager.GetString("gridError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke..
        /// </summary>
        internal static string jup {
            get {
                return ResourceManager.GetString("jup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste neispravne podatke za prijavu!.
        /// </summary>
        internal static string Login_error {
            get {
                return ResourceManager.GetString("Login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora biti veci od pet karaktera!.
        /// </summary>
        internal static string lozinka {
            get {
                return ResourceManager.GetString("lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo, popunite sva polja!.
        /// </summary>
        internal static string please {
            get {
                return ResourceManager.GetString("please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje za unos podataka!.
        /// </summary>
        internal static string podaci {
            get {
                return ResourceManager.GetString("podaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo, unesite odgovarajucu sliku!.
        /// </summary>
        internal static string slika {
            get {
                return ResourceManager.GetString("slika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status je promijenjen!.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne mozete mjenjati podatke trenutno prijavljenog korisnika!.
        /// </summary>
        internal static string status_err {
            get {
                return ResourceManager.GetString("status_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format email-a pogresan!.
        /// </summary>
        internal static string temp {
            get {
                return ResourceManager.GetString("temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo, unesite broj ili ispravite format!.
        /// </summary>
        internal static string uhvati {
            get {
                return ResourceManager.GetString("uhvati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjene su uspjesno izvrsene!.
        /// </summary>
        internal static string update_succ {
            get {
                return ResourceManager.GetString("update_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime je zauzeto!.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali korisnika!.
        /// </summary>
        internal static string user_succ {
            get {
                return ResourceManager.GetString("user_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user32 {
            get {
                object obj = ResourceManager.GetObject("user32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usluga je dodana!.
        /// </summary>
        internal static string usluga {
            get {
                return ResourceManager.GetString("usluga", resourceCulture);
            }
        }
    }
}
